sudo: required
services:
    - docker
    
before_install:
    - docker build -t gauravshindolkar/docker-react -f Dockerfile.dev .
    
script:
    - docker run gauravshindolkar/docker-react npm run test -- --coverage